name: PyInstaller Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install gettext
          brew link --force gettext

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'notifier/build.spec'
          requirements: 'notifier/requirements.txt'
          upload_exe_with_name: 'zetachain-notifier-${{ matrix.os }}'
          options: --onefile, --name "Zetachain Notifier", --icon "assets/zetachain.png"