name: PyInstaller Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install gettext
          brew link --force gettext
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/usr/local/opt/gettext/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/usr/local/opt/gettext/include"' >> $GITHUB_ENV

      - name: Set up Python on macOS
        if: matrix.os == 'macos-latest'
        run: |
          export PATH="/usr/local/opt/gettext/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/gettext/lib"
          export CPPFLAGS="-I/usr/local/opt/gettext/include"
          python -m pip install --upgrade pip

      - name: Set up Python on other OS
        if: matrix.os != 'macos-latest'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'notifier/build.spec'
          requirements: 'notifier/requirements.txt'
          upload_exe_with_name: 'zetachain-notifier-${{ matrix.os }}'
          options: --onefile, --name "ZetachainNotifier", --icon "assets/zetachain.png"